# File: apartment-application-service/azure-pipelines-master.yml

# Continuous integration (CI) triggers cause a pipeline to run whenever you push 
# an update to the specified branches or you push specified tags.
trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - README.md

# By default, use self-hosted agents
pool: Default

# Opting out of pull request validation
pr: none

resources:
  repositories:
  # Azure DevOps repository
  - repository: unittest1-pipelines
    type: git
    # project/repository
    name: unittest1/unittest1-pipelines

extends:
  template: azure-pipelines-drupal-service-test-devtest.yml@unittest1-pipelines
