<?php

namespace Drupal\asu_user\Plugin\Field\FieldType;

use Drupal\asu_user\Store;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Field\Plugin\Field\FieldType\StringItem;
use Drupal\Core\TypedData\DataDefinitionInterface;
use Drupal\Core\TypedData\TypedDataInterface;

/**
 * Variant of the 'link' field that links to the current company.
 *
 * @FieldType(
 *   id = "asu_external_string",
 *   label = @Translation("External string"),
 *   description = @Translation("External string as a field value."),
 *   default_widget = "string_textfield",
 *   default_formatter = "string",
 * )
 */
class AsuExternalString extends StringItem {
  /**
   * Whether or not the value has been calculated.
   *
   * @var bool
   */
  protected $isCalculated = FALSE;

  /**
   * Private tempstore.
   *
   * @var \Drupal\Asuntotuotanto_public\Store
   */
  private Store $store;

  /**
   * Constructor.
   */
  public function __construct(DataDefinitionInterface $definition, $name = NULL, TypedDataInterface $parent = NULL) {
    parent::__construct($definition, $name, $parent);
    $this->store = \Drupal::service('asuntotuotanto_public.tempstore');
  }

  /**
   * {@inheritdoc}
   */
  public function __get($name) {
    $this->ensureCalculated();
    return parent::__get($name);
  }

  /**
   * {@inheritdoc}
   */
  public function isEmpty() {
    $this->ensureCalculated();
    return parent::isEmpty();
  }

  /**
   * {@inheritdoc}
   */
  public function getValue() {
    $this->ensureCalculated();
    return parent::getValue();
  }

  /**
   * {@inheritdoc}
   */
  public function setValue($values, $notify = TRUE) {
    // @todo Change the autogenerated stub
    parent::setValue($values, $notify);
  }

  /**
   * Calculates the value of the field and sets it.
   */
  protected function ensureCalculated() {
    if (!$this->isCalculated) {
      $name = $this->getFieldDefinition()->getFieldStorageDefinition()->getName();
      $dataMap = \Drupal::config('asuntotuotanto_public.external_user_fields')->get('external_data_map');

      if (isset($dataMap[$name])) {
        $this->setValue([
          'value' => $this->store->get($dataMap[$name]),
        ]);
      }
      else {
        $this->setValue([
          'value' => '',
        ]);
      }
      $this->isCalculated = TRUE;
    }
  }

  /**
   * {@inheritdoc}
   */
  public static function schema(FieldStorageDefinitionInterface $field_definition) {
    return [];
  }

}
